<?php

namespace Database\Seeders;

use App\Models\Announcement;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class AnnouncementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get admin user for created_by
        $adminUser = User::where('role', 'admin')->first();
        $createdBy = $adminUser ? $adminUser->id : 1;

        $announcements = [
            [
                'title' => 'New Service Launch',
                'subtitle' => 'Introducing our latest wellness program designed for holistic health',
                'description' => "We are excited to announce the launch of our new comprehensive wellness program. This innovative service combines traditional and modern approaches to health and well-being, offering personalized care plans tailored to each individual's unique needs.\n\nOur team of experienced practitioners has developed this program after extensive research and consultation with leading health experts. The program includes regular consultations, personalized treatment plans, and ongoing support to help you achieve your health goals.\n\nBook your consultation today to learn more about how this program can benefit you.",
                'type' => 'news',
                'is_featured' => true,
                'is_published' => true,
                'expires_at' => Carbon::now()->addMonths(3),
                'order' => 1,
                'link_url' => '/services',
                'link_text' => 'View Services',
            ],
            [
                'title' => 'Holiday Schedule',
                'subtitle' => 'Important dates to remember for clinic operations',
                'description' => "Please be advised of our holiday schedule for the upcoming season. The clinic will be closed on the following dates:\n\n- December 25th (Christmas Day)\n- December 26th (Boxing Day)\n- January 1st (New Year's Day)\n\nWe will resume normal operations on January 2nd. For urgent matters during these holidays, please contact our emergency hotline at 1-800-CLINIC.\n\nWe apologize for any inconvenience and wish you a happy holiday season.",
                'type' => 'announcement',
                'is_featured' => true,
                'is_published' => true,
                'expires_at' => Carbon::now()->addMonths(1),
                'order' => 2,
                'link_url' => null,
                'link_text' => null,
            ],
            [
                'title' => 'Health Tips for Winter',
                'subtitle' => 'Expert advice for maintaining your well-being during the colder months',
                'description' => "As winter approaches, it's important to take extra care of your health. Here are some expert tips from our practitioners:\n\n1. Stay Hydrated: Even though it's cold, your body still needs plenty of water.\n2. Get Regular Exercise: Indoor activities can help maintain your fitness routine.\n3. Eat Seasonal Foods: Fresh, seasonal produce provides essential nutrients.\n4. Manage Stress: The holiday season can be stressful; take time for self-care.\n5. Get Adequate Sleep: Quality rest is crucial for immune function.\n\nRemember, prevention is better than cure. Regular check-ups can help identify potential health issues early.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => Carbon::now()->addMonths(2),
                'order' => 3,
                'link_url' => '/about',
                'link_text' => 'Learn More',
            ],
            [
                'title' => 'Special Promotion',
                'subtitle' => 'Limited time offer on wellness packages',
                'description' => "For a limited time, we're offering special discounts on our wellness packages. This is the perfect opportunity to invest in your health and well-being.\n\nAvailable packages include:\n- Basic Wellness Package: 20% off\n- Premium Wellness Package: 25% off\n- Complete Health Package: 30% off\n\nThese packages include consultations, treatments, and follow-up care. Don't miss out on this exclusive offer!\n\nTerms and conditions apply. Offer valid until the end of the month.",
                'type' => 'announcement',
                'is_featured' => true,
                'is_published' => true,
                'expires_at' => Carbon::now()->addDays(15),
                'order' => 4,
                'link_url' => '/packages',
                'link_text' => 'View Packages',
            ],
            [
                'title' => 'New Team Member',
                'subtitle' => 'Welcoming Dr. Sarah Johnson to our practice',
                'description' => "We are delighted to welcome Dr. Sarah Johnson to our team. Dr. Johnson brings over 15 years of experience in holistic medicine and specializes in integrative health approaches.\n\nWith a background in both traditional and alternative medicine, Dr. Johnson is committed to providing comprehensive, patient-centered care. She will be accepting new patients starting next month.\n\nTo schedule a consultation with Dr. Johnson, please contact our reception or book online through our patient portal.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => null,
                'order' => 5,
                'link_url' => '/team',
                'link_text' => 'Meet Our Team',
            ],
            [
                'title' => 'Telemedicine Services',
                'subtitle' => 'Now offering virtual consultations for your convenience',
                'description' => "We understand that visiting the clinic in person isn't always possible. That's why we're now offering telemedicine services for select consultations.\n\nVirtual appointments are available for:\n- Follow-up consultations\n- Medication reviews\n- General health advice\n- Mental health support\n\nOur secure video platform ensures your privacy and allows you to receive quality care from the comfort of your home. Book your virtual appointment today!",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => null,
                'order' => 6,
                'link_url' => '/services',
                'link_text' => 'Book Appointment',
            ],
            [
                'title' => 'Community Health Workshop',
                'subtitle' => 'Free workshop on stress management and mindfulness',
                'description' => "Join us for a free community health workshop focused on stress management and mindfulness techniques. This interactive session will teach you practical strategies for managing daily stress and improving your mental well-being.\n\nDate: Saturday, January 15th\nTime: 10:00 AM - 12:00 PM\nLocation: Clinic Community Room\n\nSpaces are limited, so please register in advance. This workshop is open to all community members, regardless of whether you're a current patient.\n\nRefreshments will be provided.",
                'type' => 'announcement',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => Carbon::now()->addDays(30),
                'order' => 7,
                'link_url' => null,
                'link_text' => null,
            ],
            [
                'title' => 'Updated Safety Protocols',
                'subtitle' => 'Enhanced measures to ensure your safety and well-being',
                'description' => "Your health and safety remain our top priority. We have updated our safety protocols to ensure the highest standards of care and protection for all patients and staff.\n\nKey measures include:\n- Enhanced cleaning and sanitization\n- Social distancing guidelines\n- Mandatory health screenings\n- Personal protective equipment for staff\n- Improved ventilation systems\n\nWe appreciate your cooperation and understanding as we continue to provide safe, quality healthcare services.",
                'type' => 'announcement',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => null,
                'order' => 8,
                'link_url' => null,
                'link_text' => null,
            ],
            [
                'title' => 'Research Study Participation',
                'subtitle' => 'Opportunity to contribute to advancing healthcare research',
                'description' => "We are conducting a research study on the effectiveness of integrative approaches to chronic pain management. We are looking for participants who meet certain criteria.\n\nParticipants will receive:\n- Free consultations during the study period\n- Comprehensive health assessments\n- Access to new treatment protocols\n- Contribution to medical research\n\nIf you're interested in participating, please contact our research coordinator for more information about eligibility and study requirements.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => Carbon::now()->addMonths(6),
                'order' => 9,
                'link_url' => null,
                'link_text' => null,
            ],
            [
                'title' => 'Patient Portal Upgrade',
                'subtitle' => 'New features and improved user experience',
                'description' => "We've upgraded our patient portal with new features to make managing your healthcare easier than ever. New features include:\n\n- Enhanced appointment scheduling\n- Direct messaging with your healthcare provider\n- Access to test results and medical records\n- Prescription refill requests\n- Billing and payment management\n\nLog in to your account to explore the new features. If you haven't registered yet, contact our reception to set up your account.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => null,
                'order' => 10,
                'link_url' => '/login',
                'link_text' => 'Access Portal',
            ],
            [
                'title' => 'Seasonal Allergy Management',
                'subtitle' => 'Tips and treatments for managing seasonal allergies',
                'description' => "As allergy season approaches, many patients experience symptoms that can impact their daily lives. Our practitioners offer comprehensive allergy management services.\n\nWe provide:\n- Allergy testing and identification\n- Personalized treatment plans\n- Natural and conventional treatment options\n- Lifestyle modification advice\n- Ongoing support and monitoring\n\nDon't let allergies control your life. Schedule a consultation to develop a personalized management plan that works for you.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => Carbon::now()->addMonths(4),
                'order' => 11,
                'link_url' => '/services',
                'link_text' => 'View Services',
            ],
            [
                'title' => 'Clinic Expansion',
                'subtitle' => 'New facilities and expanded services coming soon',
                'description' => "We're excited to announce that we're expanding our clinic facilities to better serve our growing community. The expansion will include:\n\n- Additional consultation rooms\n- Enhanced treatment facilities\n- Expanded waiting areas\n- New diagnostic equipment\n- Improved accessibility features\n\nConstruction is scheduled to begin next month and is expected to be completed by mid-year. We appreciate your patience during this exciting time of growth.",
                'type' => 'news',
                'is_featured' => true,
                'is_published' => true,
                'expires_at' => Carbon::now()->addMonths(8),
                'order' => 12,
                'link_url' => null,
                'link_text' => null,
            ],
            [
                'title' => 'Mental Health Awareness Month',
                'subtitle' => 'Special focus on mental health and well-being',
                'description' => "This month, we're placing special emphasis on mental health awareness. Mental health is just as important as physical health, and we're here to support you.\n\nWe offer:\n- Counseling services\n- Stress management programs\n- Support groups\n- Educational workshops\n- Referrals to specialists when needed\n\nIf you or someone you know is struggling with mental health, please reach out. Help is available, and you don't have to face challenges alone.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => Carbon::now()->addMonths(1),
                'order' => 13,
                'link_url' => '/services',
                'link_text' => 'Learn More',
            ],
            [
                'title' => 'Payment Options Update',
                'subtitle' => 'New flexible payment plans available',
                'description' => "We understand that healthcare costs can be a concern. That's why we're introducing new flexible payment plans to make quality healthcare more accessible.\n\nOptions include:\n- Monthly payment plans\n- Insurance claim assistance\n- Discounted packages\n- Sliding scale fees for qualifying patients\n\nOur billing team is available to discuss payment options that work for your situation. Contact us to learn more about how we can help make healthcare affordable for you.",
                'type' => 'announcement',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => null,
                'order' => 14,
                'link_url' => null,
                'link_text' => null,
            ],
            [
                'title' => 'Preventive Care Campaign',
                'subtitle' => 'Regular check-ups are key to maintaining good health',
                'description' => "Prevention is the best medicine. Regular health check-ups can help identify potential issues early, when they're most treatable.\n\nWe recommend:\n- Annual comprehensive health assessments\n- Regular screenings based on age and risk factors\n- Vaccination updates\n- Lifestyle counseling\n- Health monitoring\n\nSchedule your preventive care appointment today. Early detection saves lives and reduces healthcare costs in the long run.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => Carbon::now()->addMonths(3),
                'order' => 15,
                'link_url' => '/services',
                'link_text' => 'Book Appointment',
            ],
            [
                'title' => 'Draft: Upcoming Event',
                'subtitle' => 'Planning for our annual health fair',
                'description' => "We're in the early planning stages for our annual community health fair. This event will feature health screenings, educational booths, and activities for the whole family.\n\nMore details will be announced soon. Stay tuned for updates!",
                'type' => 'announcement',
                'is_featured' => false,
                'is_published' => false,
                'expires_at' => null,
                'order' => 16,
                'link_url' => null,
                'link_text' => null,
            ],
            [
                'title' => 'Nutrition Counseling Services',
                'subtitle' => 'Expert guidance for optimal nutrition and health',
                'description' => "Good nutrition is fundamental to good health. Our certified nutritionists offer personalized counseling to help you achieve your health goals through proper nutrition.\n\nServices include:\n- Personalized meal planning\n- Nutritional assessments\n- Weight management support\n- Dietary modification for health conditions\n- Educational resources\n\nWhether you're looking to improve your overall health, manage a specific condition, or optimize your athletic performance, our nutrition experts can help.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => null,
                'order' => 17,
                'link_url' => '/services',
                'link_text' => 'Learn More',
            ],
            [
                'title' => 'Expired: Summer Health Tips',
                'subtitle' => 'Stay healthy during the summer months',
                'description' => "Summer brings unique health considerations. Stay hydrated, protect your skin from sun exposure, and be mindful of heat-related illnesses.\n\nRemember to schedule your summer health check-up!",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => Carbon::now()->subMonths(2),
                'order' => 18,
                'link_url' => null,
                'link_text' => null,
            ],
            [
                'title' => 'Chronic Disease Management',
                'subtitle' => 'Comprehensive support for long-term health conditions',
                'description' => "Living with a chronic condition requires ongoing management and support. Our chronic disease management program provides comprehensive care for conditions such as diabetes, hypertension, heart disease, and more.\n\nOur approach includes:\n- Regular monitoring and assessments\n- Medication management\n- Lifestyle modification support\n- Education and self-management training\n- Coordination with specialists\n\nWe work with you to develop a personalized care plan that fits your lifestyle and helps you manage your condition effectively.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => null,
                'order' => 19,
                'link_url' => '/services',
                'link_text' => 'View Program',
            ],
            [
                'title' => 'Draft: New Technology',
                'subtitle' => 'Advanced diagnostic equipment coming soon',
                'description' => "We're investing in new diagnostic technology to improve our ability to diagnose and treat various conditions. More information will be available soon.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => false,
                'expires_at' => null,
                'order' => 20,
                'link_url' => null,
                'link_text' => null,
            ],
            [
                'title' => 'Women\'s Health Services',
                'subtitle' => 'Comprehensive care for women at every stage of life',
                'description' => "We offer comprehensive women's health services tailored to meet the unique needs of women at every stage of life. Our services include:\n\n- Well-woman exams\n- Reproductive health care\n- Menopause management\n- Bone health assessments\n- Breast health services\n- Hormonal health support\n\nOur team of experienced practitioners understands the unique health challenges women face and provides compassionate, comprehensive care.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => null,
                'order' => 21,
                'link_url' => '/services',
                'link_text' => 'View Services',
            ],
            [
                'title' => 'Pediatric Care',
                'subtitle' => 'Specialized healthcare for children and adolescents',
                'description' => "Our pediatric care services provide specialized healthcare for children from infancy through adolescence. We understand that children have unique healthcare needs.\n\nServices include:\n- Well-child visits and immunizations\n- Developmental assessments\n- Treatment of childhood illnesses\n- Behavioral health support\n- School health services\n- Parent education and support\n\nWe create a welcoming, child-friendly environment where children feel comfortable and parents feel confident in the care their children receive.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => null,
                'order' => 22,
                'link_url' => '/services',
                'link_text' => 'Learn More',
            ],
            [
                'title' => 'Senior Health Program',
                'subtitle' => 'Comprehensive healthcare services for older adults',
                'description' => "As we age, our healthcare needs change. Our senior health program is designed to address the unique health concerns of older adults.\n\nProgram features:\n- Comprehensive geriatric assessments\n- Medication review and management\n- Fall prevention programs\n- Memory and cognitive health support\n- Chronic disease management\n- Coordination with specialists\n\nWe're committed to helping seniors maintain their independence and quality of life through proactive healthcare management.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => null,
                'order' => 23,
                'link_url' => '/services',
                'link_text' => 'View Program',
            ],
            [
                'title' => 'Draft: Community Outreach',
                'subtitle' => 'Plans for increased community engagement',
                'description' => "We're developing new community outreach programs to better serve our local community. Details will be announced in the coming months.",
                'type' => 'announcement',
                'is_featured' => false,
                'is_published' => false,
                'expires_at' => null,
                'order' => 24,
                'link_url' => null,
                'link_text' => null,
            ],
            [
                'title' => 'Insurance Coverage Update',
                'subtitle' => 'We now accept additional insurance plans',
                'description' => "We're pleased to announce that we now accept additional insurance plans, making our services more accessible to more patients.\n\nAccepted plans include:\n- Major health insurance providers\n- Medicare and Medicaid\n- Employer-sponsored plans\n- Individual health plans\n\nPlease contact our billing department to verify your coverage and understand your benefits. We're here to help you navigate insurance questions.",
                'type' => 'announcement',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => null,
                'order' => 25,
                'link_url' => null,
                'link_text' => null,
            ],
            [
                'title' => 'Exercise and Fitness',
                'subtitle' => 'Incorporating physical activity into your health plan',
                'description' => "Regular physical activity is essential for maintaining good health. Our practitioners can help you develop an exercise plan that's safe, effective, and enjoyable.\n\nWe provide:\n- Fitness assessments\n- Personalized exercise prescriptions\n- Guidance for various fitness levels\n- Support for exercise-related health conditions\n- Integration with your overall health plan\n\nWhether you're just starting out or looking to optimize your current routine, we can help you achieve your fitness goals safely.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => null,
                'order' => 26,
                'link_url' => '/services',
                'link_text' => 'Get Started',
            ],
            [
                'title' => 'Sleep Health Program',
                'subtitle' => 'Addressing sleep issues for better overall health',
                'description' => "Quality sleep is crucial for physical and mental health. Our sleep health program helps identify and address sleep-related issues.\n\nWe offer:\n- Sleep assessments and evaluations\n- Treatment for sleep disorders\n- Sleep hygiene education\n- Lifestyle modifications\n- Referrals to sleep specialists when needed\n\nIf you're experiencing sleep problems, don't suffer in silence. Help is available, and better sleep can significantly improve your quality of life.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => null,
                'order' => 27,
                'link_url' => '/services',
                'link_text' => 'Learn More',
            ],
            [
                'title' => 'Draft: Annual Report',
                'subtitle' => 'Preparing our annual community health report',
                'description' => "We're compiling our annual report on community health trends and our clinic's impact. The report will be published early next year.",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => false,
                'expires_at' => null,
                'order' => 28,
                'link_url' => null,
                'link_text' => null,
            ],
            [
                'title' => 'Patient Feedback',
                'subtitle' => 'Your opinion matters - help us improve our services',
                'description' => "We value your feedback and are always looking for ways to improve our services. Your input helps us provide better care and enhance the patient experience.\n\nWays to share feedback:\n- Patient satisfaction surveys\n- Direct communication with staff\n- Online reviews\n- Suggestion box\n\nWe review all feedback regularly and use it to make meaningful improvements. Thank you for helping us serve you better.",
                'type' => 'announcement',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => null,
                'order' => 29,
                'link_url' => null,
                'link_text' => null,
            ],
            [
                'title' => 'Wellness Wednesday',
                'subtitle' => 'Weekly wellness tips and health information',
                'description' => "Join us every Wednesday for Wellness Wednesday, where we share tips, information, and resources to help you maintain and improve your health.\n\nEach week, we'll cover different topics including:\n- Nutrition and healthy eating\n- Exercise and physical activity\n- Mental health and stress management\n- Preventive care\n- Managing chronic conditions\n\nFollow us on social media or check our website every Wednesday for new content. Small changes can lead to big improvements in your health!",
                'type' => 'news',
                'is_featured' => false,
                'is_published' => true,
                'expires_at' => null,
                'order' => 30,
                'link_url' => null,
                'link_text' => null,
            ],
        ];

        foreach ($announcements as $announcement) {
            Announcement::create(array_merge($announcement, [
                'created_by' => $createdBy,
                'created_at' => Carbon::now()->subDays(rand(0, 90)),
                'updated_at' => Carbon::now()->subDays(rand(0, 90)),
            ]));
        }

        $this->command->info('Created ' . count($announcements) . ' announcements successfully.');
    }
}
