@props([
    'mobileCardView' => true,
    'tableId' => null,
    'class' => ''
])

@php
    $tableId = $tableId ?? 'table_' . uniqid();
@endphp

<div class="table-responsive-wrapper {{ $class }}" data-table-id="{{ $tableId }}">
    <!-- Desktop Table View -->
    <div class="desktop-table-view overflow-x-auto -mx-4 sm:mx-0">
        <div class="inline-block min-w-full align-middle">
            {{ $slot }}
        </div>
    </div>
    
    <!-- Mobile Card View -->
    @if($mobileCardView)
        <div class="mobile-table-view hidden md:hidden" id="{{ $tableId }}_mobile">
            <!-- Cards will be generated by JavaScript -->
        </div>
    @endif
</div>

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    const wrapper = document.querySelector('[data-table-id="{{ $tableId }}"]');
    if (!wrapper) return;
    
    const table = wrapper.querySelector('table');
    if (!table) return;
    
    // Initialize mobile table conversion if needed
    if (typeof MobileTable !== 'undefined') {
        MobileTable.init('{{ $tableId }}', {
            breakpoint: 768
        });
    }
});
</script>
@endpush

