@extends('layouts.admin')

@section('content')
    <div class="space-y-6">
        <div class="mx-auto">
            <!-- Header -->
            <div class="flex items-center justify-between mb-8">
                <div class="flex items-center gap-4">
                    <a href="{{ route('admin.payrolls.index') }}"
                        class="bg-white p-2 rounded-full shadow-sm hover:shadow-md transition-shadow text-gray-600">
                        <i class='bx bx-arrow-back text-2xl'></i>
                    </a>
                    <div>
                        <h1 class="text-3xl font-bold text-gray-800">Payslip Details</h1>
                        <p class="text-gray-600 mt-1">View payroll information</p>
                    </div>
                </div>

                <div class="flex gap-2">
                    <button onclick="printPayslip()"
                        class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center gap-2">
                        <i class='bx bx-printer'></i> Print
                    </button>
                    <button onclick="downloadPayslip()"
                        class="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center gap-2">
                        <i class='bx bx-download'></i> Download
                    </button>
                    @if($payroll->status === 'draft')
                        <button onclick="approvePayroll({{ $payroll->id }})"
                            class="bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center gap-2">
                            <i class='bx bx-check-circle'></i> Approve
                        </button>

                        <a href="{{ route('admin.payrolls.edit', $payroll->id) }}"
                            class="bg-yellow-500 hover:bg-yellow-600 text-white px-4 py-2 rounded-lg transition-colors flex items-center gap-2">
                            <i class='bx bx-edit'></i> Edit
                        </a>

                        <form action="{{ route('admin.payrolls.destroy', $payroll->id) }}" method="POST" class="delete-form">
                            @csrf
                            @method('DELETE')
                            <button type="submit"
                                class="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center gap-2">
                                <i class='bx bx-trash'></i> Delete
                            </button>
                        </form>
                    @elseif($payroll->status === 'approved')
                        <button onclick="markAsPaid({{ $payroll->id }})"
                            class="bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center gap-2">
                            <i class='bx bx-dollar'></i> Mark as Paid
                        </button>
                    @endif
                </div>
            </div>

            <!-- Payslip Card -->
            <div class="bg-white rounded-xl shadow-lg overflow-hidden">
                <div class="p-8">
                    @include('admin.payrolls.payslip_template', ['payroll' => $payroll])
                </div>

                <!-- Notes -->
                @if($payroll->notes)
                    <div class="px-8 pb-8">
                        <h3 class="text-sm font-semibold text-gray-500 uppercase mb-2">Notes</h3>
                        <div class="bg-gray-50 p-4 rounded-lg border border-gray-200">
                            <p class="text-gray-700">{{ $payroll->notes }}</p>
                        </div>
                    </div>
                @endif

                <!-- Audit Information -->
                <div class="bg-gray-50 px-8 py-4 border-t border-gray-200">
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-gray-600">
                        <div>
                            <p><span class="font-medium">Generated By:</span> {{ $payroll->generatedBy->name ?? 'N/A' }}</p>
                            <p><span class="font-medium">Generated On:</span>
                                {{ $payroll->created_at->format('M d, Y h:i A') }}</p>
                        </div>
                        @if($payroll->approved_by)
                            <div>
                                <p><span class="font-medium">Approved By:</span> {{ $payroll->approvedBy->name }}</p>
                                <p><span class="font-medium">Approved On:</span>
                                    {{ $payroll->approved_at->format('M d, Y h:i A') }}</p>
                            </div>
                        @endif
                        @if($payroll->status === 'paid')
                            <div>
                                <p><span class="font-medium">Payment Date:</span> {{ $payroll->payment_date ? $payroll->payment_date->format('M d, Y') : 'N/A' }}</p>
                                <p><span class="font-medium">Payment Reference:</span> {{ $payroll->payment_reference ?? 'N/A' }}</p>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
    <script>
        // Print Payslip
        function printPayslip() {
            const content = document.getElementById('payslip-content');
            const printWindow = window.open('', '_blank');
            printWindow.document.write(`
                <!DOCTYPE html>
                <html>
                <head>
                    <title>Payslip - {{ $payroll->pay_period ?? 'N/A' }} - {{ $payroll->user->name ?? 'Employee' }}</title>
                    <script src="https://cdn.tailwindcss.com"><\/script>
                    <style>
                        @media print {
                            body { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
                        }
                    </style>
                </head>
                <body class="p-8">
                    ${content.outerHTML}
                    <script>
                        window.onload = function() {
                            setTimeout(function() {
                                window.print();
                                window.close();
                            }, 500);
                        };
                    <\/script>
                </body>
                </html>
            `);
            printWindow.document.close();
        }

        // Download Payslip as PDF
        function downloadPayslip() {
            const element = document.getElementById('payslip-content');
            const opt = {
                margin: 10,
                filename: 'Payslip-{{ $payroll->pay_period ?? 'N-A' }}-{{ Str::slug($payroll->user->name ?? 'Employee') }}.pdf',
                image: { type: 'jpeg', quality: 0.98 },
                html2canvas: { scale: 2 },
                jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
            };
            html2pdf().set(opt).from(element).save();
        }

        // Approve Payroll
        function approvePayroll(payrollId) {
            Swal.fire({
                title: 'Approve Payroll?',
                text: "This will approve the payslip for payment.",
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#10b981',
                cancelButtonColor: '#6b7280',
                confirmButtonText: 'Yes, approve it!',
                cancelButtonText: 'Cancel'
            }).then((result) => {
                if (result.isConfirmed) {
                    const form = document.createElement('form');
                    form.method = 'POST';
                    form.action = `/admin/payrolls/${payrollId}/approve`;

                    const csrfToken = document.createElement('input');
                    csrfToken.type = 'hidden';
                    csrfToken.name = '_token';
                    csrfToken.value = '{{ csrf_token() }}';
                    form.appendChild(csrfToken);

                    document.body.appendChild(form);
                    form.submit();
                }
            });
        }

        // Mark as Paid
        function markAsPaid(payrollId) {
            Swal.fire({
                title: 'Mark as Paid',
                text: "Enter the payment reference number (optional):",
                input: 'text',
                inputPlaceholder: 'Payment Reference (e.g., TRX12345)',
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#8b5cf6',
                cancelButtonColor: '#6b7280',
                confirmButtonText: 'Yes, mark as paid!',
                cancelButtonText: 'Cancel'
            }).then((result) => {
                if (result.isConfirmed) {
                    const form = document.createElement('form');
                    form.method = 'POST';
                    form.action = `/admin/payrolls/${payrollId}/mark-as-paid`;

                    const csrfToken = document.createElement('input');
                    csrfToken.type = 'hidden';
                    csrfToken.name = '_token';
                    csrfToken.value = '{{ csrf_token() }}';
                    form.appendChild(csrfToken);

                    const referenceInput = document.createElement('input');
                    referenceInput.type = 'hidden';
                    referenceInput.name = 'payment_reference';
                    referenceInput.value = result.value;
                    form.appendChild(referenceInput);

                    document.body.appendChild(form);
                    form.submit();
                }
            });
        }

        // Delete Confirmation
        document.querySelectorAll('.delete-form').forEach(form => {
            form.addEventListener('submit', function (e) {
                e.preventDefault();
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#ef4444',
                    cancelButtonColor: '#6b7280',
                    confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        form.submit();
                    }
                });
            });
        });
    </script>
@endsection